<a href="https://colab.research.google.com/github/Abdullah2020/Hamoye_StageA/blob/main/Test1_Hamoye.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#convention for importing numpy

import numpy as np

arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [2]:
a = np.array(arr)

print(type(a))       #the type of class
print(a.shape)       #print shape or ID array of a

print(a.dtype)      #print the dtype (int64)

print(a.ndim)       #get the dimension of 'a' with ndim

<class 'numpy.ndarray'>
(4,)
int64
1


In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])

print(b)

#print the dimension
print('The dimension of b is = ', b.ndim)

b.shape

[[1 2 3]
 [4 5 6]]
The dimension of b is =  2


(2, 3)

In [7]:
#inbuilt functions

np.random.random((2, 3))       #create a random of 2x3 array wiht random values


array([[0.74984149, 0.76577799, 0.04316086],
       [0.53274733, 0.92616509, 0.44778129]])

In [8]:
np.zeros((2, 3))    #create 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 4))      #create 2x4 array with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
#Intra-operability of Arrays and Scalars.

c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

print(c + d)
print(c * d)

5 / d

c ** 2

[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]


array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [12]:
#Indexing With Arrays & Using Arrays for Data Processing

a[0]       #display the first index of a

b[0, 0]

print(d[1, 0:2])        #select the second index of d from 0  to 2 internal index.




[9. 8.]


In [15]:
#slicing index

e = np.array([[10, 11, 12], [13, 14, 15,], [16, 17, 18], [19, 20, 21]])

e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [19]:
#integer indexing

e[[2 , 0 , 3, 1], [2, 1, 0, 2]]

#boolean indexing meeting a specified condition
e[e!=19]        #index and print any number but 19
#e.mean()
#e.std()
#e.min()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21])

File Input and Output With Arrays Numpy arrays can be loaded from and saved to binary files with **.npy ** as the extension using **load()** and **save()** respectively. This can also be done with text files with text files using **loadtxt()** and** savetxt()**.

#Pandas - So Much More Than A Cute Animal


In [20]:
import pandas as pd

In [28]:
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])

print(days)
days.shape

0       Monday
1      Tuesday
2    Wednesday
dtype: object


(3,)

In [29]:
#creating series with a numpy array
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days = pd.Series(days_list)

print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [30]:
#using strings as index
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'], 
                 index = ['a', 'b', 'c'])

print(days)


a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [33]:
#create series from a dictionary
days1 = pd.Series({'a':'Monday', 'b':'Tuesday', 'c':'Wednesday'})
days1

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [36]:
days[2]
days[1:]
days['c']

'Wednesday'

A **DataFrame** can be described as a table (2 dimensions) made up of many series with the same index. It holds data in rows and columns just like a spreadsheet. Series, dictionaries, lists, other dataframes, and numpy arrays can be used to create new ones.

In [37]:
print(pd.DataFrame())       #prints an empty dataframe

Empty DataFrame
Columns: []
Index: []


In [46]:
#create a dataframe from a dictionary

df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'], 
           'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
           'Population':[10000, 8500, 35000, 12000],
           'Age':[60, 70, 80, 75]}

df1 = pd.DataFrame(df_dict, index = [2, 4, 6, 8])

df_list = (['Ghana', 'Accra',10000, 60],
           ['Kenya', 'Nairobi', 8500, 70],
           ['Nigeria', 'Abuja', 35000, 80],
           ['Togo', 'Lome', 12000, 75])
df2 = pd.DataFrame(df_list, columns = ['Country', 'Capital', 'Population', 'Age'],
                   index = [1,2,3,4])

df2


Country  Capital  Population  Age
1    Ghana    Accra       10000   60
2    Kenya  Nairobi        8500   70
3  Nigeria    Abuja       35000   80
4     Togo     Lome       12000   75

**at, iat, iloc** and **loc** are accessors used to retrieve data in dataframes. iloc selects values from the rows and columns by using integer index to locate positions, while loc selects rows or columns using labels. at and iat are used to retrieve single values such that at uses the column and row labels and iat uses indices.

In [44]:
#select the row in the index 3 (using integer index)
df1.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [58]:
#select row with index label 6 (using labels)

df1.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [52]:
#select the Capital column
df1['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [64]:
#selecting using .at and .iat

df1.at[6, 'Country']

'Nigeria'

In [70]:
#descriptive statistics

df1['Population'].sum()
df1.mean()
df1.describe(include= 'all')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.


Country Capital    Population        Age
count        4       4      4.000000   4.000000
unique       4       4           NaN        NaN
top      Ghana   Accra           NaN        NaN
freq         1       1           NaN        NaN
mean       NaN     NaN  16375.000000  71.250000
std        NaN     NaN  12499.166639   8.539126
min        NaN     NaN   8500.000000  60.000000
25%        NaN     NaN   9625.000000  67.500000
50%        NaN     NaN  11000.000000  72.500000
75%        NaN     NaN  17750.000000  76.250000
max        NaN     NaN  35000.000000  80.000000

The missing data enigma: Importance, types and handling missing data.
Often, data used for analysis in real life scenarios is incomplete as a result of omission, faulty devices, and many other factors. Pandas represent missing values as NA or NaN which can be filled, removed, and detected with functions like **fillna(), dropna(), isnull(), notnull(), replace()**.

In [73]:
#missing values

df_dict2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
            'Profession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
            'Experience': [12, np.nan, 10, 8],
            'Height': [np.nan, 175, 180, 150]}

new_df = pd.DataFrame(df_dict2)
new_df

Name  Profession  Experience  Height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [78]:
#new_df.describe(include='all')

#check for cells with missing values as True
new_df.isnull()

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [79]:
#remove rows with missing values
new_df.dropna()

Name Profession  Experience  Height
2  Caro     Doctor        10.0   180.0

**Fuel Dataset Analysis**

In [80]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv?raw=true'

fuel_data = pd.read_csv(url, error_bad_lines=False)
fuel_data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [83]:
#check for missing values

fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [87]:
#use groupby to count the sum of each unique value in the fuel_unit column

fuel_data.groupby('fuel_unit')['fuel_unit'].count()

#fill the missing values with the highest uniques variable in the column i.e mcf
fuel_data[['fuel_unit']] = fuel_data[['fuel_unit']].fillna(value='mcf')

In [90]:
#check for missing values again

print(fuel_data)
fuel_data.isnull().sum()


                     record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton      

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [92]:
fuel_df1 = fuel_data.iloc[0:19000].reset_index(drop=True)
fuel_df2 = fuel_data.iloc[19000:].reset_index(drop=True)

#check that the length of both dataframes sum to the expected length
assert len(fuel_data) == (len(fuel_df1) + len(fuel_df2))

#An inner merge will lose rows that do not match in both dataframes
pd.merge(fuel_df1, fuel_df2, how='inner')

Empty DataFrame
Columns: [record_id, utility_id_ferc1, report_year, plant_name_ferc1, fuel_type_code_pudl, fuel_unit, fuel_qty_burned, fuel_mmbtu_per_unit, fuel_cost_per_unit_burned, fuel_cost_per_unit_delivered, fuel_cost_per_mmbtu]
Index: []

In [93]:
#Outer merge returns all rows in both dataframes
pd.merge(fuel_df1, fuel_df2, how='outer')

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [94]:
#Removes rows from the right dataframe that do not have a matach with the left
#and keeps all rows from the left
pd.merge(fuel_df1, fuel_df2, how='left')


record_id  utility_id_ferc1  report_year  \
0         f1_fuel_1994_12_1_0_7                 1         1994   
1        f1_fuel_1994_12_1_0_10                 1         1994   
2         f1_fuel_1994_12_2_0_1                 2         1994   
3         f1_fuel_1994_12_2_0_7                 2         1994   
4        f1_fuel_1994_12_2_0_10                 2         1994   
...                         ...               ...          ...   
18995   f1_fuel_2009_12_182_1_9               182         2009   
18996  f1_fuel_2009_12_182_1_10               182         2009   
18997  f1_fuel_2009_12_182_1_13               182         2009   
18998  f1_fuel_2009_12_182_1_14               182         2009   
18999    f1_fuel_2009_12_79_0_1                79         2009   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
18995             lake road                 gas       mcf         340857.0   
18996             lake road                 oil       mcf            771.0   
18997           iatan (18%)                coal       ton         414142.0   
18998           iatan (18%)                 oil       bbl           5761.0   
18999              montrose                coal       ton        2050919.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                16.590000                     18.590   
1                16.592000                     18.580   
2                24.130000                     39.720   
3                23.950000                     47.210   
4                 1.000000                      2.770   
...                    ...                        ...   
18995             1.000000                      4.711   
18996             5.801544                     84.899   
18997            16.718000                     18.509   
18998             5.537910                     83.636   
18999            17.160000                     29.629   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                            18.530                1.121  
1                            18.530                1.120  
2                            38.120                1.650  
3                            45.990                1.970  
4                             2.770                2.570  
...                             ...                  ...  
18995                         4.711                4.711  
18996                        84.899               14.634  
18997                        17.570                1.107  
18998                        72.280               15.102  
18999                        28.330                1.727  

[19000 rows x 11 columns]